const experiences = [
	{
		title: 'Tech Lead',
		companyName: 'Medicomp Solutions',
		icon: '/assets/experience/yeats-logo.png',
		iconBg: '#383E56',
		date: 'Nov 2019 - Mar 2021',
		points: [
			'Built & Deployed a Tele-medicine platform and integrate it with existing EHR system. ',
			'Built and deployed an EHR system for a hospital in the US for iPad',
			'Built new features such as SMS,Email, Fax integration, and more.',
			'Upgrade existing .Net backend and fixed issues with Progress Notes',
			'Added Notice board feature',
			'Designed and developed a new UI for the EHR system.',
		],
	},
	{
		title: 'CTO',
		companyName: 'Slide',
		icon: '/assets/experience/slide-logo.png',
		iconBg: '#383E56',
		date: 'Mar 2020 - Oct 2020',
		points: [
			'Developed an online Web Event',
			'Built Dashboard system for the event organizer',
			'Integrated Stripe Payment Gateway',
			'Integrated Chime SDK',
			'Added Chat, Q&A, and Polling features',
			'Added Live Streaming feature',
			'Added Ticketing feature',
			'Added Sponsorship feature',
			'Added Analytics feature',
		],
	},
	{
		title: 'Founding Engineer / Senior Software Engineer',
		companyName: 'Addinex',
		icon: '/assets/experience/addinex-logo.png',
		iconBg: '#E6DEDD',
		date: 'Mar 2021 - Nov 2022',
		points: [
			'Designed backend System Architecture',
			'Designed and developed Application UI',
			'Designed and developed a Web Application using React.js/Next.js',
			'Integrated mobile app with backend API',
		],
	},
	{
		title: 'Tech Lead',
		companyName: 'Bazar',
		icon: '/assets/experience/bazar-logo.png',
		iconBg: '#383E56',
		date: 'Nov 2021 - June 2023',
		points: [
			'Led a team of 6 developers ',
			'Upgraded code standards and features',
			'Developed E-Commerce Web Application using React.js/Next.js',
			'Developed API endpoints using Node.js/Nestjs',
			'Added Apple/Google Pay Integration',
			'Added Product Creation, Product Management, and Order Management features',
			'Added Notification System',
			'Added Robust Component Library using Storybook',
			'Added Testing Library using Playwright',
			,
		],
	},
	{
		title: 'Founding Engineer / Head of Engineering',
		companyName: 'Fingu',
		icon: '/assets/experience/fingu-logo-dark.png',
		iconBg: '#E6DEDD',
		date: 'March 2022 - July 2023',
		points: [
			'Built a learning Web Application using React.js/Next.js',
			'Designed and built API with GraphQL',
			'Set up CI/CD with Jenkins and AWS',
			'Built Dashboard for Admin to upload courses and manage users',
			'Integrated Stripe Payment Gateway',
			'Built Investors club ( A youtube like feature )',
		],
	},
];

export default experiences;
